config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root "photos#index"
  resources :photos

  resources :users, only: %i[show update destroy]

  get 'access_denied', to: 'pages#access_denied'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user&.admin?
      can :manage, :all
    else
      can :read, :all
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/photo.rb
# frozen_string_literal: true

class Photo < ApplicationRecord
  mount_uploader :image, ImageUploader
  before_create :set_random_id
  validates :title, :description, presence: true

  private

  def set_random_id
    self.random_id = SecureRandom.hex(10) unless random_id.present?
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def admin?
    admin
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# The base controller for the application, from which all other controllers inherit.

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[email password password_confirmation admin])
    devise_parameter_sanitizer.permit(:account_update,
                                      keys: %i[email password password_confirmation current_password admin])
  end

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || photos_path
  end

  def after_sign_out_path_for(_resource)
    photos_path
  end

  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { head :forbidden, content_type: 'text/html' }
      format.html { redirect_to access_denied_url, notice: exception.message }
      format.js   { head :forbidden, content_type: 'text/html' }
    end
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true
#added for custom access denied page

class PagesController < ApplicationController
  def access_denied
    # This action will render the custom access denied page
  end
end

app/controllers/photos_controller.rb
# frozen_string_literal: true

# The controller to maintain photo details  and other CRUD operations

class PhotosController < ApplicationController
  load_and_authorize_resource except: :create
  before_action :authenticate_user!, except: %i[index show]
  def index
    @photos = Photo.all
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photos_params)
    authorize! :create, @photo
    if @photo.save
      redirect_to @photo
    else
      logger.debug @photo.errors.full_messages
      render 'new'
    end
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def update
    @photo = Photo.find(params[:id])
    if @photo.update(photos_params)
      redirect_to @photo, notice: 'Cat photo updated successfully!'
    else
      logger.debug @photo.errors.full_messages.to_sentence
      render 'edit'
    end
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    redirect_to photos_path
  end

  def show
    @photo = Photo.find(params[:id])
    return unless @photo.nil?

    redirect_to photos_path, alert: 'Photo not found.'
  end

  private

  def photos_params
    params.require(:photo).permit(:title, :description, :image)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true
# The controller to maintain user details authentication and authorization

class UsersController < ApplicationController
  before_action :set_user, only: %i[show update destroy]
  before_action :authenticate_user!
  before_action :check_admin, only: [:destroy]

  def show
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      redirect_to @user, notice: 'User was not updated.'
    end
  end

  def destroy
    @user.destroy
    Rails.logger.info "Failed to destroy user: #{@user.errors.full_messages}"
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :admin)
  end

  # Check if the current user is an admin
  def check_admin
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/photos_helper.rb
# frozen_string_literal: true

module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <% if user_signed_in? %>
  <%= form_with url: destroy_user_session_path, method: :delete do %>
    <%= submit_tag 'Logout' %>
  <% end %>
  
  <% else %>
    <%= link_to 'Login', new_user_session_path %>
    <%= link_to 'Register', new_user_registration_path %>
  <% end %>

  <%= yield %>
</body>
</html>

app/views/pages/access_denied.html.erb
<h1>Access Denied</h1>
<p>You do not have permission to view this page.</p>
<%= link_to 'Back', photos_path %>

app/views/photos/edit.html.erb
<%= form_with(model: @photo, local: true) do |form| %>
    <%= form.label :title %>
    <%= form.text_field :title %>

    <%= form.label :description %>
    <%= form.text_area :description %>
    
    <%= form.file_field :image %>
    <%= form.submit "Update Cat Photo" %>

    <%= link_to 'Back', photos_path %>
<% end %>

app/views/photos/index.html.erb
<h1>All Photos</h1>
<%= link_to 'Upload New Photo', new_photo_path %>
<% @photos.each do |photo| %>
  <div>
    <%= image_tag photo.image.thumb.url if photo.image? %>
    <%= link_to 'Show', photo %>
    <%= link_to 'Edit', edit_photo_path(photo) %>
    
    <%= form_for photo, url: photo_path(photo), method: :delete, data: { confirm: 'Are you sure?' } do |f| %>
      <%= f.submit 'Delete' %>
    <% end %>
  </div>
<% end %>
<% if @photos.empty? %>
  <p>No photos available.</p>
<% end %>

app/views/photos/new.html.erb
<%= form_with(model: @photo, local: true) do |form| %>
    <%= form.label :title %>
    <%= form.text_field :title %>

    <%= form.label :description %>
    <%= form.text_area :description %>
    
    <%= form.file_field :image %>
    <%= form.submit "Upload" %>
  <% end %>
  

app/views/photos/show.html.erb
<p>
    <strong>Title:</strong>
    <%= @photo.title %>
</p>

<p>
    <strong>Description:</strong>
    <%= @photo.description %>
</p>    

<%= image_tag @photo.image.url %>

<div>
<%= link_to 'Back', photos_path %>
</div>